[project]
name = 'Community-Urban-Planning'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fund-allocation]
path = 'contracts/fund-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.government-api-integration]
path = 'contracts/government-api-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-nft]
path = 'contracts/project-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.project-proposal]
path = 'contracts/project-proposal.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting-mechanism]
path = 'contracts/voting-mechanism.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
